### ISSUE TITLE
write_stream / read_stream abstractions removed

### ISSUE THREAD

**Issue by itdaniher** [kevinmehall/rust-usb#15]
When/why? I liked them, going to need to reimplement them elsewhere if not here.

**Comment by kevinmehall** [comment]
Pulled when I ripped out the backend thread and all the stuff that was necessary when Rust threads were green threads; simply haven't gotten around to reimplementing them.

**Comment by kevinmehall** [comment]
https://github.com/kevinmehall/rust-usb/commit/fa6b1d1f257d26a2500e53b402d7d130fa22938d
